### ISSUE TITLE
How can I send response to a cmd to server?

### ISSUE THREAD

**Issue by raengi** [ruby/net-telnet#17]
When I send a `host.cmd('comand')` the server waits for a second command for confirmation, how can I do that?
if I send a second host.cmd('yes'), the problem: Net::ReadTimeout with "timed out while waiting for more data" because the host close connection.

**Comment by znz** [comment]
If confirmation prompt exists, `"Prompt"` of `Net::Telnet::new` set regexp matches normal prompt and confirmation prompt.

e.g. `Net::Telnet.new("Prompt" => /[$%#>] \z|\[yn\]\? \z/)`

**Comment by raengi** [comment]
Hey, thanks!
