### ISSUE TITLE
Connect to a host with no prompt?

### ISSUE THREAD

**Issue by simonbrazell** [ruby/net-telnet#8]
Hello, is it possible to do this?

The host I'm connecting to does not have a prompt but you can issue commands upon connection and get a response. Currently I'm trying this with the following:

```
telnet = Net::Telnet::new(
        'Host' => HOST,
        'Port' => PORT,
        'Timeout' => false,
        'Prompt' => /.*/
)
```
But it fails with `A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. - connect(2) for HOST port PORT.` .

If I can connect I was thinking I could then use `'Match'` when calling `cmd` to match the end of the command output instead of the prompt, but I can't connect.

I'd really appreciate any help you can offer.

**Comment by znz** [comment]
How about using `socket` directly instead of `net/telnet`?

**Comment by simonbrazell** [comment]
Hello @znz, yes this was actually what I was thinking of doing next as no matter what I do I can't seem to establish a connection to the server using  `Net::Telnet::new` even though I can telnet to the server using puTTY or the CLI, so I guess I have to go lower, just haven't done that before. 

Just wanted to know if it was possible using `net/telnet`.

Thanks for responding!

**Comment by znz** [comment]
I did not understand error message correctly.
Error on connect does not related prompt.
It seems to related to network problem. Check your firewall, etc.

**Comment by simonbrazell** [comment]
Never mind, it turned out that the person who asked me to write the script had given me the wrong IP for the host... very frustrating... sorry to waste your time.
